name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  generate:
    name: Generate snake from contributions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure assets directory exists
        run: mkdir -p assets

      - name: Generate snake SVGs (svg-only)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@users.noreply.github.com
          message: "chore: update generated github-snake images"
          add: "assets/github-snake.svg assets/github-snake-dark.svg"
          push: true
